version: '3.9'

services:
    db:
        image: postgres:16
        container_name: finance_db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: finance
        ports:
            - '5433:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

    app:
        build: .
        container_name: finance_app
        restart: always
        depends_on:
            - db
        environment:
            NODE_ENV: production
            DB_HOST: db
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_NAME: finance
            DB_PORT: 5432
            PORT: 3001
            TZ: 'America/Sao_Paulo'
        ports:
            - '3001:3001'
        command: ['node', 'server.js']

volumes:
    postgres_data:
